#import "../template.typ": *

#show: note

With the following exceptions:

- Website architecture
- Trivial, repetitive writing
- Illustrations
- Template development

I do not use AI tools to write the mathematical content of these notes. I write the material myself and, as xiaou0, take full responsibility for its correctness. Most notes are written while I am learning, so please forgive any mistakes.

#remark[
  In other words, 99.9% of the content you read was typed by me, rather than generated by AI under my supervision. Some proofs or ideas may originate from language models, but I work through and rewrite them in my own words.
]
